### ISSUE TITLE
flathub permission file system to use matrix download location

### ISSUE THREAD

**Issue by candrapersada** [flathub/net.agalwood.Motrix#4]
add filesystem=host by default to use the download location.

**Comment by proletarius101** [comment]
That's not necessary to download to another location, as long as you choose the location in the `Save to` field upon job creation once.

**Comment by proletarius101** [comment]
Maybe we lost in translation. I mean, you don't need `filesystem=host` to download to any locations, as long as you choose `Save to` once. It's strongly insecure to set `filesystem=host` in any circumstances, by the way.

**Comment by proletarius101** [comment]
Setting `filesystem=host` is rather dangerous. `--filesystem=home` will be an acceptable temporary solution.

`GtkFileChooserNative` has merged and will be landed in Electron 14 (electron/electron#19159). It will not be an issue when Motrix adopts Electron 14.
